version: "3.8"

services:
  sql-agent:
    image: sql-agent:latest
    networks:
      - mind
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=mind
        - traefik.http.routers.sql-agent.rule=Host(`portfolio.mindthedata.com.br`)
        - traefik.http.routers.sql-agent.entrypoints=websecure
        - traefik.http.routers.sql-agent.tls=true
        - traefik.http.routers.sql-agent.tls.certresolver=letsencryptresolver
        - traefik.http.services.sql-agent.loadbalancer.server.port=3000

networks:
  mind:
    external: true
